name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile asmigar
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile asmigar
        aws configure set region ${{ secrets.AWS_REGION }} --profile asmigar

    - name: Login to Amazon ECR
      id: login-ecr
      run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} --profile asmigar | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URL }}
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.7
        
    # - name: Debug S3 bucket name
    #   run: echo "hello-world-terraform-state-97eb1079"

    # - name: Initialize Terraform in remote_state
    #   working-directory: infra/accounts/dev/remote_state
    #   run: terraform init

    # - name: Apply Terraform in remote_state
    #   working-directory: infra/accounts/dev/remote_state
    #   run: terraform apply -auto-approve

    # - name: Get Terraform output
    #   id: terraform_output
    #   run: |
    #     cd infra/accounts/dev/remote_state
    #     terraform output -json > terraform_output.json
    #     echo "::set-output name=s3_bucket::$(cat terraform_output.json | jq -r '.terraform_state_bucket_name.value')"

    - name: Initialize Terraform in ecs
      working-directory: infra/accounts/dev/ecs
      run: terraform init -backend-config="bucket=${{ secrets.S3_BUCKET_NAME }}"

    - name: Apply Terraform in ecs
      working-directory: infra/accounts/dev/ecs
      run: terraform apply -auto-approve 
      
    - name: Build Docker image
      working-directory: src
      run: docker build -t ${{ secrets.ECR_REPOSITORY_URL }}:${{ secrets.TF_VAR_release_version }} .

    - name: Push Docker image to Amazon ECR
      working-directory: src
      run: docker push ${{ secrets.ECR_REPOSITORY_URL }}:${{ secrets.TF_VAR_release_version }}

    - name: Apply Terraform configuration
      working-directory: infra/accounts/dev/ecs
      run: terraform apply -auto-approve -var="release_version=${{ secrets.TF_VAR_release_version }}"
